NAME = btphone-gui
DIR = /usr/share
CC = pyinstaller
ARGS = -D
DEPS = ./*.py
INS = cp -r
WD = build_d

$(NAME): $(DEPS)
    $(CC) $(ARGS) $(DEPS) -n $(NAME)

install: $(NAME)
    $(INS) $(NAME) $(DIR)
